[pytest]
markers = e2e: pruebas end to end
        compra: flujo de compra
        smoke: pruebas smoke
        regression: pruebas regression

addopts = -v --html=reports/e2e_report.html --self-contained-html
testpaths = tests
python_files = test_*.py
